### ISSUE TITLE
html code doesn't work

### ISSUE THREAD

**Issue by zBugi** [workshops-de/angular.de#82]
Hi i am new to Angular and Webdevelopment but is this working as intendet ?
cause when I used this the text allways was hidden even if I pressed the button and fixed that this tag is not closed.
```html
<p>info-box works!</p>
<button (click)="hidden=!hidden">
<p [hidden]="true">{{text}}</p>
```

I guess what u where trying to show was:
```html
<p>info-box works!</p>
<button (click)="hidden=!hidden">toggle</button>
<p [hidden]="hidden">{{text}}</p>
```

cause otherwise that gif would not be the compiled code
![](https://angular.de/artikel/angular-tutorial-deutsch/info-box-toggle.gif)

**Comment by robinboehm** [comment]
Good catch! Thanks!
