### ISSUE TITLE
Create new angular app 

### ISSUE THREAD

**Issue by aeropagz** [workshops-de/angular.de#85]
You write in the text, that you should choose routing but in example you write "NO".

`Hierbei werdet ihr gefragt ob ihr das Routing Module installieren wollt: Ja. `
`Would you like to add Angular routing? No`

Also I experienced some errors after implementing the HTTPClientModule which were fixed by restarting the angular app. Maybe you could create a hint for this.

**Comment by robinboehm** [comment]
Hey, @aeropagz thanks for the feedback! Just fixed it in 875490a.
Can you give some more detailed explanation for your errors with the HTTPClientModule? 

Thanks :)

**Comment by aeropagz** [comment]
Ah great! 
Yes sure console error was:
`Error: src/app/book-list/book-list.component.ts:12:10 - error TS2314: Generic type 'Observable<T>' requires 1 type argument(s).        
12  books$: Observable;`

**Comment by robinboehm** [comment]
Ah! We can avoid that by beginning with a typed generic 6dc23d0e3091db82a5d4e389a2927f64da8e9df9

fixed! Thanks!
