### ISSUE TITLE
2 Probleme in Angular Tutorial

### ISSUE THREAD

**Issue by Redsmith24** [workshops-de/angular.de#89]
Haalo Robin,
ich bin ein absolute beginner was Angular angeht und auf der Suche nach einer Einführung bin ich auf dieses Tutorial gestoßen. Vieln Dank schoon einmal dafür.
An 2 Stellen bin ich auf Fehlermeldungen gestoßen, die ich im Rahmen des Tutorials nicht lösen konnte.
So gab es bei der Einführung der dependency injection immer die Fehlermeldung:
error TS2304: Cannot find name 'BookDataService'
Ich hatte den Eindruck, das Tutorial richtet sich an Anfänger. Da ist es natürlich schwer an diese Stelle irgenwie weiter zu kommen. Durch die Recherche auf anderen Seiten und AUsprobiren habe ich dann herausgefunden, dass die neue Klasse auch importiert werden muss:
import { BuchdatenService } from '../book-data.service';
Das steht leider nicht im Tutorial oder habe ich das überlesen?
Später dann beim Thema „Umgang mit Asychronität“ gibt es eine weitere Fehlermeldung:
error TS2304: Cannot find name 'Observable'.
Wieder durch suchen und Ausprobiren habe ich dann gefunden, dass dies das Problem löst:
import { Observable } from 'rxjs';
Wobei ich nicht weiß, ob dies die einzige oder beste Lösung ist.
Auch das habe ich in dem Tutorial nicht gefunden. Keine Ahnung ob andere diese Fehler nicht haben, auf jeden Fall wäre es ja schön, wenn man ein solches Tutorial ohne solche Hindernisse nachvollziehen könnte.
Alle anderen Schritte sind ausreichend und verständlich erklärt.
Inagesamt wäre es schön im Anschluss gleich an zweites Beispiel zu haben um besser zu verstehen, was das vorgegebene System ist und was kann durch den Entwickler variabel gesetzt werden kann.

**Comment by robinboehm** [comment]
Hallo @Redsmith24 !!

Super Feedback, danke dir vielmals! Das ist mir wohl tatsächlich durchgegangen!
Versuch das diese Woche nachzustellen =)

Danke das du die Community und die Qualität des Portals mit unterstützt! =)

Robin

**Comment by robinboehm** [comment]
Vielleicht schafft es @web-dave ja auch früher wie auch mal drüber zu schauen und zu fixen. *liebguck*
Aktuell geh ich etwas unter auf der Arbeit, sorry

**Comment by robinboehm** [comment]
Hey @Redsmith24 - ist nun gefixt und wir haben Hinweise eingebaut! Vielen Lieben Dank!

**Comment by Redsmith24** [comment]
Ja, danke für den Einbau. Mich würde noch interessieren, wovon das abhängig ist, ob die IDE die beiden Dinge automatisch integriert oder nicht. Gibt es da eine Erklärung?

**Comment by robinboehm** [comment]
Also die meisten in der Community nutzen zur Zeit Visual Studio Code würde ich behaupten: https://code.visualstudio.com/
Ich glaube ich hab das dort nicht extra aktiviert. Nutzt du die gleiche IDE oder eine andere?
WebStorm sollte das auch ohne Probleme können, habe ich auch sehr lange und gerne benutzt.

Ich hab dazu noch die Angular Language Server IDE Extension. Die gibt nochmal viele zusätzliche Hints.
https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

Der Import sollte aber auch unabhängig davon funktionieren.
